### ISSUE TITLE
Jak to działa? 

### ISSUE THREAD

**Issue by tomkolp** [sirinsidiator/weblate-customizations#1]
What is this code for?  How to use it with lua and weblate files?

**Comment by sirinsidiator** [comment]
This repo contains all the customizations I made for https://weblate.sir.insidi.at/or/ to be able to scan and export code for [LibGetText](https://www.esoui.com/downloads/info2276-LibGetText.html). The intention is not really for others to use this directly themselves, but rather in case someone wants to contribute.
I'm still in the process of figuring out a proper workflow for onboarding new projects, but once I'm done with that, I plan to write a guide on how other authors can use it for their own addons and request their project to be added to the weblate instance I'm hosting. My idea is to provide this as a free service for others and make translating addons easier for everyone.

**Comment by tomkolp** [comment]
We have our own instance https://weblate.eso-spolszczenie.eu/.  I thought this code was used to convert lua to .pot.  We create a Polish translation on weblate and we have a translation memory that is useful for translating add-ons.  I downloaded the AwesomeGuildStore_messages.pot file for testing and uploaded it to our weblate.  Once completed, the .po translation will be uploaded to your weblate installation.

**Comment by sirinsidiator** [comment]
Ah. I wasn't aware of that.
In theory the exporter code should also be able to import Lua files and store them in weblate's format, but for some reason it won't accept Lua files on upload and since I don't really need that, I didn't look into it further.
I actually set the projects to protected atm, so you won't be able to upload it unless you create a user and I add you to the project. That aside, the polish translation already was completed. Unless there are some improvements you want to make, there is currently no real need to translate them from scratch? Maybe you could instead take a look at https://weblate.sir.insidi.at/or/projects/aetheriusbadgefilter/messages/?

**Comment by tomkolp** [comment]
GeneralEU is one of the Scribes of Tamriel. He managed to upload translations exported from https://weblate.eso-spolszczenie.eu/ . The most important thing for us is to have access to .pot files (they are currently hosted on github).

**Comment by sirinsidiator** [comment]
You can actually get them from inside weblate by downloading the zip file containing all translations from the component view: https://weblate.sir.insidi.at/or/download/aetheriusbadgefilter/messages/?format=zip

**Comment by tomkolp** [comment]
Access denied
 Insufficient permissions to view this page.

**Comment by sirinsidiator** [comment]
You need to be logged in to access the download I believe.

**Comment by tomkolp** [comment]
It's working now.
